sudo: false

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake .. -DENABLE_GCOV_SUPPORT=ON
  - make
  - ./unit_tests

after_success:
  - coveralls --root .. -E ".*3rd-party.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
